### ISSUE TITLE
Tool version specification

### ISSUE THREAD

**Issue by skanwal** [umccr/cwl-ica-cli#107]
With the current cli `v1.4.1`, we get an error when specifying versions for tools with alphabetic suffix such as STAR https://quay.io/repository/biocontainers/star?tab=tags. 

```
$ cwl-ica create-tool-from-template --tool-name star --tool-version 2.7.10b
2023-01-06 08:19:45,683 - ERROR    - create_from_template      - check_shlex_version_arg                  : LineNo. 124  - Was not able to parse 2.7.10b as a version for parameter --tool-version
Traceback (most recent call last):
  File "/Users/kanwals/miniconda/envs/cwl-ica/bin/cwl-ica", line 13, in <module>
    sys.exit(main())
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/utils/cli.py", line 649, in main
    _dispatch()
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/utils/cli.py", line 305, in _dispatch
    create_tool_obj = CreateToolFromTemplate(command_argv)
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/subcommands/creators/create_tool_from_template.py", line 76, in __init__
    self.check_args()
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/subcommands/creators/create_tool_from_template.py", line 104, in check_args
    self.check_shlex_version_arg("--tool-version", tool_version_arg)
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/subcommands/creators/create_from_template.py", line 128, in check_shlex_version_arg
    raise InvalidVersionError
utils.errors.InvalidVersionError
```

Adding support for this use case will be useful, IMO.

**Comment by alexiswl** [comment]
This is a conflict with the semantic version specifications at https://semver.org/ rather than an issue with anything in cwl-ica

I'd recommend specifying the version as `2.7.0--b` instead.  

Happy to raise an issue in STAR on this.  

```python
>>> from semantic_version import Version
>>> Version("2.7.0b")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alexiswl/mambaforge/envs/cwl-ica/lib/python3.10/site-packages/semantic_version/base.py", line 105, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/home/alexiswl/mambaforge/envs/cwl-ica/lib/python3.10/site-packages/semantic_version/base.py", line 318, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '2.7.0b'
>>> Version("2.7.0--b")
Version('2.7.0--b')
```

**Comment by alexiswl** [comment]
@skanwal reluctant to make any changes to this. Using the semver parser saves a lot of otherwise manual regex hacking on our side.  I am happy to submit a PR to the STAR GitHub page to see if they will change the versioning syntax for releases but would otherwise recommend the `--b` workaround.

**Comment by skanwal** [comment]
> would otherwise recommend the --b workaround.

Sounds good to me.

**Comment by alexiswl** [comment]
Suggestion added to STAR - https://github.com/alexdobin/STAR/issues/1738
