### ISSUE TITLE
Workflow submission template failes with 'not-so-simple' multiple types

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica-cli#116]
## Command that caused this error

```bash
cwl-ica create-workflow-submission-template \
  --workflow-path /home/alexiswl/GitHub/UMCCR/cwl-ica/workflows/dragen-somatic-pipeline/4.0.3/dragen-somatic-pipeline__4.0.3.cwl \
  --prefix multiqc-tn-test-1-14 \
  --project development_workflows \
  --launch-project development \
  --ica-workflow-run-instance-id wfr.25f2c89ce8954d038fdbf268d7cc70c9 \
  --gds-prefix gds://development/temp/alexis/multiqc-tn-test/
```

## Traceback

```pytb
2023-01-16 20:46:40,198 - WARNING  - create_submission_template - get_cwl_inputs_from_object               : LineNo. 416  - Can't handle multiple types that aren't simple
2023-01-16 20:46:40,199 - INFO     - create_submission_template - __call__                                 : LineNo. 116  - Writing out input yaml file to multiqc-tn-test-1-14.template.yaml
2023-01-16 20:46:40,200 - WARNING  - input_template_utils      - get_commented_map_for_input_object       : LineNo. 190  - Cannot add eol to input repeat_genotype_use_catalog
2023-01-16 20:46:40,200 - WARNING  - input_template_utils      - get_commented_map_for_input_object       : LineNo. 190  - Cannot add eol to input sample_sex
Traceback (most recent call last):
  File "/home/alexiswl/miniforge3/envs/cwl-ica/bin/cwl-ica", line 13, in <module>
    sys.exit(main())
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/utils/cli.py", line 649, in main
    _dispatch()
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/utils/cli.py", line 511, in _dispatch
    create_workflow_template_obj()
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/subcommands/query/create_submission_template.py", line 117, in __call__
    self.write_yaml_file()
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/subcommands/query/create_submission_template.py", line 533, in write_yaml_file
    yaml_h.dump(self.input_template_object)
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/site-packages/ruamel/yaml/main.py", line 570, in dump
    self._context_manager.dump(data)
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/site-packages/ruamel/yaml/main.py", line 915, in dump
    self._yaml.representer.represent(data)
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/site-packages/ruamel/yaml/representer.py", line 80, in represent
    node = self.represent_data(data)
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/site-packages/ruamel/yaml/representer.py", line 103, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/site-packages/ruamel/yaml/representer.py", line 1034, in represent_dict
    return self.represent_mapping(tag, data)
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/site-packages/ruamel/yaml/representer.py", line 869, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/site-packages/ruamel/yaml/representer.py", line 103, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/site-packages/ruamel/yaml/representer.py", line 1034, in represent_dict
    return self.represent_mapping(tag, data)
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/site-packages/ruamel/yaml/representer.py", line 869, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/site-packages/ruamel/yaml/representer.py", line 113, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/site-packages/ruamel/yaml/representer.py", line 354, in represent_undefined
    raise RepresenterError(_F('cannot represent an object: {data!s}', data=data))
ruamel.yaml.representer.RepresenterError: cannot represent an object: dragen-somatic-pipeline--4.0.3/repeat_genotype_use_catalog/default
```

**Comment by alexiswl** [comment]
This appears to be the input that has tripped us up!

```
  vc_enable_unequal_ntd:
    label: vc enable unequal ntd
    doc: |
      Nucleotide (NTD) Error Bias Estimation is on by default and recommended as a replacement for the orientation bias filter. 
      Both methods take account of strand-specific biases (systematic differences between F1R2 and F2R1 reads). 
      In addition, NTD error estimation accounts for non-strand-specific biases such as sample-wide elevation of a certain SNV type, 
      eg C->T or any other transition or transversion. 
      NTD error estimation can also capture the biases in a trinucleotide context.
    type:
      - "null"
      - boolean
      - type: enum
        symbols:
          - "true"
          - "false"
          - "auto"
```
