### ISSUE TITLE
cwl-ica icav2-zip-workflow --output-path should check if output is of type File and if parent exists

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica-cli#118]
```
cwl-ica icav2-zip-workflow \
  --workflow-path workflows/bclconvert-with-qc-pipeline/4.0.3/bclconvert-with-qc-pipeline__4.0.3.cwl --output-path bclconvert-qc.zip
```

Results in 

```
2023-02-05 20:40:13,206 - ERROR    - zip_v2_workflow           - check_args                               : LineNo. 126  - Expected --output-path set as /c/Users/awluc/OneDrive/GitHub/UMCCR/cwl-ica/bclconvert-qc.zip, is expected to exist
Traceback (most recent call last):
  File "/home/alexiswl/miniforge3/envs/cwl-ica/bin/cwl-ica", line 13, in <module>
    sys.exit(main())
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.8/utils/cli.py", line 642, in main
    _dispatch()
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.8/utils/cli.py", line 603, in _dispatch
    zip_v2_workflow = ZipV2Workflow(command_argv)
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.8/subcommands/v2/zip_v2_workflow.py", line 86, in __init__
    self.check_args()
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.8/subcommands/v2/zip_v2_workflow.py", line 127, in check_args
    raise CheckArgumentError
utils.errors.CheckArgumentError
```

**Comment by alexiswl** [comment]
This command has been deprecated, so won't fix, instead will remove all 'icav2*' commands from the cwl-ica cli repo, use icav2-cli-plugins instead
