### ISSUE TITLE
Gremlins with boolean inputs set to false not being recognised as inputs for create submission template

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica-cli#147]
```
cwl-ica create-workflow-submission-template   --workflow-path "${CWL_ICA_REPO_PATH}/workflows/dragen-somatic-pipeline/4.0.3/dragen-somatic-pipeline__4.0.3.cwl"   --project development_workflows   --ica-workflow-run-instance-id wfr.4b9df435e8794f8b9842a8cb12277bf3   --launch-project development   --prefix "tumor_bam_input_test_v4"   --gds-prefix gds://development/temp/alexis/somatic_bam_input_testing/   --ignore-workflow-id-mismatch
2023-03-07 10:17:24,784 - WARNING  - cwl_schema                - get_sanitised_object                     : LineNo. 187  - Don't know what to do with key read_1
2023-03-07 10:17:24,784 - WARNING  - cwl_schema                - get_sanitised_object                     : LineNo. 188  - ordereddict([('label', 'read 1'), ('doc', 'The path to R1 of a sample\n'), ('type', ['File', 'string']), ('streamable', True)])
2023-03-07 10:17:24,785 - WARNING  - cwl_schema                - get_sanitised_object                     : LineNo. 196  - Expected a dict to be left for read_1
2023-03-07 10:17:24,785 - WARNING  - cwl_schema                - get_sanitised_object                     : LineNo. 197  - Got ordereddict([('label', 'read 1'), ('doc', 'The path to R1 of a sample\n'), ('type', ['File', 'string']), ('streamable', True)])
2023-03-07 10:17:24,826 - WARNING  - cwl_schema                - get_sanitised_object                     : LineNo. 187  - Don't know what to do with key read_1
2023-03-07 10:17:24,827 - WARNING  - cwl_schema                - get_sanitised_object                     : LineNo. 188  - ordereddict([('label', 'read 1'), ('doc', 'The path to R1 of a sample\n'), ('type', ['File', 'string']), ('streamable', True)])
2023-03-07 10:17:24,827 - WARNING  - cwl_schema                - get_sanitised_object                     : LineNo. 196  - Expected a dict to be left for read_1
2023-03-07 10:17:24,827 - WARNING  - cwl_schema                - get_sanitised_object                     : LineNo. 197  - Got ordereddict([('label', 'read 1'), ('doc', 'The path to R1 of a sample\n'), ('type', ['File', 'string']), ('streamable', True)])
2023-03-07 10:17:24,827 - WARNING  - create_submission_template - get_cwl_inputs_from_object               : LineNo. 425  - Can't handle multiple types that aren't simple
2023-03-07 10:17:24,828 - INFO     - create_submission_template - __call__                                 : LineNo. 116  - Writing out input yaml file to tumor_bam_input_test_v4.template.yaml
2023-03-07 10:17:24,850 - INFO     - create_submission_template - __call__                                 : LineNo. 120  - Decorating input yaml file with inputs from wfr.4b9df435e8794f8b9842a8cb12277bf3
2023-03-07 10:17:24,914 - INFO     - utils                     - _init_num_threads                        : LineNo. 160  - NumExpr defaulting to 4 threads.
2023-03-07 10:17:25,389 - ERROR    - create_submission_template - decorate_yaml_file                       : LineNo. 585  - Items in instance are not in yaml object
2023-03-07 10:17:25,389 - ERROR    - create_submission_template - decorate_yaml_file                       : LineNo. 586  - Missing inputs: enable_sort
Traceback (most recent call last):
  File "/home/alexiswl/miniforge3/envs/cwl-ica/bin/cwl-ica", line 13, in <module>
    sys.exit(main())
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/utils/cli.py", line 656, in main
    _dispatch()
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/utils/cli.py", line 512, in _dispatch
    create_workflow_template_obj()
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/subcommands/query/create_submission_template.py", line 121, in __call__
    self.decorate_yaml_file()
  File "/home/alexiswl/miniforge3/envs/cwl-ica/lib/python3.10/subcommands/query/create_submission_template.py", line 587, in decorate_yaml_file
    raise ValueError
ValueError
```

But 
```
ica workflows runs get wfr.4b9df435e8794f8b9842a8cb12277bf3 -o json | jq '.input | fromjson | keys'
[
  "bam_input",
  "enable_duplicate_marking",
  "enable_map_align",
  "enable_map_align_output",
  "enable_sort",
  "enable_sv",
  "output_directory",
  "output_file_prefix",
  "reference_tar",
  "tumor_bam_input"
]
```

**Comment by alexiswl** [comment]
Outsmarted by my own code, turns out enable_sort is NOT part of the dragen somatic pipeline, adding it in
