### ISSUE TITLE
Create catalogue step fails with tool catalogue not existing

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica-cli#157]
```
2023-03-07T07:31:08.5844115Z Traceback (most recent call last):
2023-03-07T07:31:08.5844651Z   File "/home/cwl_ica_user/.conda/envs/cwl-ica/bin/cwl-ica", line 13, in <module>
2023-03-07T07:31:08.5845042Z     sys.exit(main())
2023-03-07T07:31:08.5845609Z   File "/home/cwl_ica_user/.conda/envs/cwl-ica/lib/python3.10/utils/cli.py", line 656, in main
2023-03-07T07:31:08.5846005Z     _dispatch()
2023-03-07T07:31:08.5846563Z   File "/home/cwl_ica_user/.conda/envs/cwl-ica/lib/python3.10/utils/cli.py", line 551, in _dispatch
2023-03-07T07:31:08.5846994Z     create_tool_markdown_obj()
2023-03-07T07:31:08.5847648Z   File "/home/cwl_ica_user/.conda/envs/cwl-ica/lib/python3.10/subcommands/github_actions/create_markdown_file.py", line 160, in __call__
2023-03-07T07:31:08.5848146Z     md_file.create_md_file()
2023-03-07T07:31:08.5848769Z   File "/home/cwl_ica_user/.conda/envs/cwl-ica/lib/python3.10/site-packages/mdutils/mdutils.py", line 71, in create_md_file
2023-03-07T07:31:08.5849281Z     md_file = MarkDownFile(self.file_name)
2023-03-07T07:31:08.5850047Z   File "/home/cwl_ica_user/.conda/envs/cwl-ica/lib/python3.10/site-packages/mdutils/fileutils/fileutils.py", line 25, in __init__
2023-03-07T07:31:08.5850724Z     self.file = open(f'{self.dirname}/{self.file_name}', 'w+', encoding='UTF-8')
2023-03-07T07:31:08.5853501Z FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/cwl-ica/cwl-ica//home/runner/work/cwl-ica/cwl-ica/.github/catalogue/docs/tools/dragen-germline/3.9.3/dragen-germline__3.9.3.md'
```

**Comment by alexiswl** [comment]
File path looks like it could be the issue here:

'
'/home/runner/work/cwl-ica/cwl-ica//home/runner/work/cwl-ica/cwl-ica/.github/catalogue/docs/tools/dragen-germline/3.9.3/dragen-germline__3.9.3.md'
'

**Comment by alexiswl** [comment]
Looks like this could be the issue: https://github.com/didix21/mdutils/issues/81

Solution is "to downgrade to 1.4.0"? 

Really should move to SnakeMD sooner rather than later (https://github.com/umccr/cwl-ica-cli/issues/106)
