### ISSUE TITLE
ModuleNotFoundError: No module named 'filelock'

### ISSUE THREAD

**Issue by skanwal** [umccr/cwl-ica-cli#182]
Getting following error with `cwl-ica` (v1.5.8)

```
$ cwl-ica tool-init --tool-path tools/arriba-fusion-calling/2.4.0/arriba-fusion-calling__2.4.0.cwl --projects development_workflows
2023-06-05 13:52:00,413 - INFO     - cwl_tool                  - validate_object                          : LineNo. 144  - Running cwltool --validate "tools/arriba-fusion-calling/2.4.0/arriba-fusion-calling__2.4.0.cwl"
2023-06-05 13:52:02,936 - WARNING  - subprocess_handler        - run_subprocess_proc                      : LineNo. 41   - Received exit code "1" for command "'conda'" "'run'" "'--name'" "'cwltool-icav1'" "'cwltool'" "'--validate'" "'tools/arriba-fusion-calling/2.4.0/arriba-fusion-calling__2.4.0.cwl'"
2023-06-05 13:52:02,936 - WARNING  - subprocess_handler        - run_subprocess_proc                      : LineNo. 47   - Stdout was:
""
2023-06-05 13:52:02,936 - WARNING  - subprocess_handler        - run_subprocess_proc                      : LineNo. 49   - Stderr was:
"INFO /Users/kanwals/miniconda/envs/cwltool-icav1/bin/cwltool 3.0.20201203173111
Traceback (most recent call last):
  File "/Users/kanwals/miniconda/envs/cwltool-icav1/lib/python3.8/site-packages/cachecontrol/caches/file_cache.py", line 74, in __init__
    from filelock import FileLock
ModuleNotFoundError: No module named 'filelock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kanwals/miniconda/envs/cwltool-icav1/bin/cwltool", line 8, in <module>
    sys.exit(run())
  File "/Users/kanwals/miniconda/envs/cwltool-icav1/lib/python3.8/site-packages/cwltool/main.py", line 1287, in run
    sys.exit(main(*args, **kwargs))
  File "/Users/kanwals/miniconda/envs/cwltool-icav1/lib/python3.8/site-packages/cwltool/main.py", line 923, in main
    loadingContext = setup_loadingContext(loadingContext, runtimeContext, args)
  File "/Users/kanwals/miniconda/envs/cwltool-icav1/lib/python3.8/site-packages/cwltool/main.py", line 712, in setup_loadingContext
    loadingContext.loader = default_loader(
  File "/Users/kanwals/miniconda/envs/cwltool-icav1/lib/python3.8/site-packages/cwltool/load_tool.py", line 70, in default_loader
    return Loader(
  File "/Users/kanwals/miniconda/envs/cwltool-icav1/lib/python3.8/site-packages/schema_salad/ref_resolver.py", line 178, in __init__
    cache=FileCache(root / ".cache" / "salad"),
  File "/Users/kanwals/miniconda/envs/cwltool-icav1/lib/python3.8/site-packages/cachecontrol/caches/file_cache.py", line 84, in __init__
    raise ImportError(notice)
ImportError:
NOTE: In order to use the FileCache you must have
filelock installed. You can install it via pip:
  pip install filelock


ERROR conda.cli.main_run:execute(49): `conda run cwltool --validate tools/arriba-fusion-calling/2.4.0/arriba-fusion-calling__2.4.0.cwl` failed. (See above for error)"
2023-06-05 13:52:02,936 - ERROR    - cwl                       - run_cwltool_validate                     : LineNo. 231  - cwltool validate failed when run in conda environment cwltool-icav1 with cwltool version 3.0.20201203173111
Traceback (most recent call last):
  File "/Users/kanwals/miniconda/envs/cwl-ica/bin/cwl-ica", line 13, in <module>
    sys.exit(main())
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/utils/cli.py", line 656, in main
    _dispatch()
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/utils/cli.py", line 370, in _dispatch
    tool_init_obj = ToolInitialiser(command_argv)
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/subcommands/initialisers/tool_init.py", line 56, in __init__
    super(ToolInitialiser, self).__init__(command_argv,
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/subcommands/initialisers/initialiser.py", line 96, in __init__
    self.item_version = self.create_item_version_object()
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/subcommands/initialisers/tool_init.py", line 140, in create_item_version_object
    item_version()
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/classes/item_version.py", line 63, in __call__
    self.set_cwl_object()
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/classes/item_version_tool.py", line 70, in set_cwl_object
    self.cwl_obj.validate_object()
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/classes/cwl_tool.py", line 145, in validate_object
    self.run_cwltool_validate(self.cwl_file_path)
  File "/Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/classes/cwl.py", line 233, in run_cwltool_validate
    raise CWLValidationError
utils.errors.CWLValidationError
```

Tried pip installing filelock but seems the dependency already has been installed:

```
 $ pip install filelock
Requirement already satisfied: filelock in /Users/kanwals/miniconda/envs/cwl-ica/lib/python3.10/site-packages (3.12.0)
```

**Comment by alexiswl** [comment]
Error is in the environment `cwltool-icav1`, not `cwl-ica`. Can you try installing into that environment?
